spring:
  application:
    name: only-bank
  autoconfigure:
    exclude:
  jackson:
    serialization:
      write-dates-as-timestamps: false
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 20MB

  datasource:
    url: jdbc:oracle:thin:@//localhost:1521/bankdb.localdomain
    username: bank
    password: bank
    driver-class-name: oracle.jdbc.OracleDriver

  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true

  sleuth:
    sampler:
      probability: 0.1

  flyway:
    baseline-on-migrate: true

  management:
    endpoints:
      web:
        exposure:
          include: "*"
          exclude: beans,env
